### ISSUE TITLE
Run onn MAC

### ISSUE THREAD

**Issue by ficast** [mreintz/circleOfFifths#1]
How can I run this on a mac OS?

**Comment by mreintz** [comment]
Hi!

I don't own a Mac myself, but Mac OS comes with python preinstalled and should be able to run the same packages, though there are no guarantees since I haven't tested it on that platform. As stated on the home page for the project, the code runs on python with the following requirements:

- PyQt5==5.15.1
- musthe==1.0.0

I can't give you step by step instructions, but Google is your friend on how to upgrade python on your Mac, how to install git or just unpackage my code, how do install the required packages with pip or some other package manager, and how to run the code from the Mac Terminal app.

Good luck! And I'd like to know how well it works on Mac OS once you've tested it.

Morten
